version: 3
services:
  mcbot1:
    image: dockermcbot:latest
    volumes:
      - minecraft:/srv/minecraft
    deploy:
      mode: global
    ports:
      - 10001:8000
  mcbot0:
    image: dockermcbot:latest
    volumes:
      - minecraft:/srv/minecraft
    deploy:
      mode: global
    ports:
      - 10002:8000
volumes:
  minecraft:
    external: true
