version: '3.8'
services:
  mcbot:
    image: dockermcbot:latest
    volumes:
      - minecraft:/srv/minecraft
    deploy:
      mode: replicated
      replicas: 10
    ports:
      - 8000-8010:8000
volumes:
  minecraft:
    external: true