POST http://localhost:8000/disconnect

###

POST http://localhost:8000/sendmsg
Content-Type: application/json

{"message": "#test"}

###

POST http://localhost:8000/connect
Content-Type: application/json

{
  "address": "10.1.1.174",
  "port": 25565
}

###

# curl "localhost:8000/status"
GET localhost:8000/status
Accept: application/json

<> 2020-07-10T045404.200.json

###

# curl "localhost:8000/player"
GET localhost:8000/player
Accept: application/json

###

# curl "localhost:8000/chat"
GET http://localhost:8000/chat
Accept: application/json

<> 2020-07-10T045412.200.json

###